### ISSUE TITLE
客户端共用同一个swoole_client的冲突问题

### ISSUE THREAD

**Issue by andot** [xcl3721/Dora-RPC#2]
如果在同一个程序中创建两个客户端，分别连接不同的服务器，比如：

第一个客户端连接 127.0.0.1:3000, 第二个客户端连接 127.0.0.1:3001，因为共用同一个 swoole_client，会造成冲突，无法使用。

**Comment by xcl3721** [comment]
收到～开始修复～

**Comment by xcl3721** [comment]
fixed
