### ISSUE TITLE
关于rpc的一个疑问

### ISSUE THREAD

**Issue by gouchaoer** [xcl3721/Dora-RPC#26]
如果rpc是阻塞的，那么在等待rpc返回的这段时间里php进程就没有别的事可做就进程饥饿，就很难支持大qps了。。。就算使用的异步的httpclient如果有一个wait的过程那还是有进程饥饿，dora用的是swoole1。x版本吧，这个问题是如果解决的呢？

**Comment by gouchaoer** [comment]
swoole2。x的io函数本身有协程应该没这个问题

**Comment by xcl3721** [comment]
dora是使用长连接tcp通讯的，下发任务的时候会生成一个标识符标识此次请求，在收到服务端返回的下发成功信息就继续做其他事情去了，并没有等待这个结果（仅限于客户单异步下发最后拿结果模式）。当服务端处理完毕返回给客户端的时候，客户端这是还没有执行接收，数据只是在客户端的缓存里面，客户端在发送其他请求给服务端的时候顺便把之前的任务结果拿回来扔到一个地方存放。还有一个函数，最后统一将所有下发过的连接扫描一遍，拿到所有的结果。用户调用接口的时候从数组中找到对应结果，发给用户

**Comment by xcl3721** [comment]
协程版本，对于本次请求也是等待的……
